spring.application.name=YouthBridge

spring.datasource.url=jdbc:mariadb://localhost:3302/youthbridge
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

springdoc.swagger-ui.path=/swagger-ui.html

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB